version: '3'
services:
  web:
    image: python:3.8-alpine
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      sh -c "python -m pip install -r requirements.txt &&
             python gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app"
    ports:
      - "5000:5000"
